spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.1.88}:${DB_PORT:5435}/${DB_NAME:bookstoreonline}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:All4one7!}
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
